modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="scorcheddimension"
version="0.1"
displayName="Scorched dimension"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Krich01, MCreator"
description='''
Scorched dimension is there! Enjoy!
'''

[[dependencies.scorcheddimension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.scorcheddimension]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0]"
    ordering="NONE"
    side="BOTH"


[[dependencies.scorcheddimension]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

